highlighter:    pygments
markdown: 		kramdown
paginate:       10

title:          ACM HONORED CLASS
baseurl:        ""
url:            ""
permalink:      /:categories/:title/

author:
    name:       GilbertHeywood
    email:      5304618a@gmail.com
    twitter:    none
    
footer:
      
copyright:
    - Design by ACM HONORED CLASS
    - "&copy; Copyright 2014, ACM HONORED CLASS. All Rights Reserved."
      
css:
    - /lib/style.css
    - /lib/syntax.css
    - /lib/buttons.css
    
