highlighter:    pygments
markdown: 		kramdown
paginate:       10
paginate_path:	"news/page:num"

title:          ACM HONORED CLASS
baseurl:        "http://fei960922.github.io/ACM_Website_2014/new_website/"
url:            "http://fei960922.github.io/ACM_Website_2014/new_website/"
permalink:      /:categories/:title/

author:
    name:       GilbertHeywood
    email:      5304618a@gmail.com
    twitter:    none
    
footer:
      
copyright:
    - Design by ACM HONORED CLASS
    - "&copy; Copyright 2014, ACM HONORED CLASS. All Rights Reserved."
      
css:
    - /lib/style.css
    - /lib/syntax.css
    - /lib/buttons.css
    
